name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd mario-kart-tournament
          git pull origin main
          npm install
          pm2 restart mario-kart-tournament